<a href="https://colab.research.google.com/github/aicrashcoursewinter24/CSC-480_Gerardo_Madera_repo/blob/lab_2_branch/notebooks/gpt-exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
print("Gerardo's Lab 2 gpt-exploration")

Gerardo's Lab 2 gpt-exploration


Today, we'll play with turning text into numeric vectors (the process of "vectorization"), which first requires splitting up the a long string into something closer to a list of words (or characters).

This latter process is the process of "tokenization": each word/sub-word/character (the atomic unit of text) is called a "token".

Start by installing the "datasets" python package, giving you access to some helpful utilities in downloading public datasets from HuggingFace and elsewhere.

In [1]:
! pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.1/507.1 kB 5.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 7.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 9.1 MB/s eta 0:00:00


There are pre-built tokenizer models, which have both code and mappings between tokens and token *ids* - integers which will be feature columns for the text

We will first use the BERT model (the original "transformer" from the "[Attention is All You Need](https://arxiv.org/abs/1706.03762)" paper), in a form which knows how to differentiate between lower and uppercase characters (some tokenizers lowercase everything first).  It's called "bert-base-uncased".

In [2]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

Note in the output above, you should see a comment about the "HF_TOKEN" secret.  There is also a link to HuggingFace, where you can generate your HF Token (see note below about the word "token"). To the left part of the Colab screen, there is a "key" icon: you can store your HF_TOKEN as a secret there.  Name it HF_TOKEN and give it "notebook access" via the toggle.


--

 note on "token": there are now two completely unrelated uses of the word "token" in this lab:

* "token": a unit of text like a word or character (or even multi-word phrase) used in text preprocessing
* "HF_TOKEN": a password-like thing for getting access to HuggingFace

In [3]:
encoded = tokenizer.encode("Do not meddle in the affairs of wizards")

In [4]:
# prompt: write python code to print the textule tokens in sequential order from a string, using the above tokenizer

encoded = tokenizer.encode("Do not meddle in the affairs of wizards")
tokens = tokenizer.convert_ids_to_tokens(encoded)
print(tokens)


['[CLS]', 'Do', 'not', 'me', '##ddle', 'in', 'the', 'affairs', 'of', 'wizard', '##s', '[SEP]']


In [7]:
# prompt: write python code to print the textual tokens in sequential order from a string, using the above tokenizer

print(tokenizer.convert_ids_to_tokens(encoded))


['[CLS]', 'Do', 'not', 'me', '##ddle', 'in', 'the', 'affairs', 'of', 'wizard', '##s', '[SEP]']


In [8]:
print(encoded)

[101, 2091, 1136, 1143, 13002, 1107, 1103, 5707, 1104, 16678, 1116, 102]


In [9]:
encoded_input = tokenizer("Do not meddle in the affairs of wizards, for they are subtle and quick to anger.")
print(encoded_input.keys())
print(encoded_input['input_ids'])

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])
[101, 2091, 1136, 1143, 13002, 1107, 1103, 5707, 1104, 16678, 1116, 117, 1111, 1152, 1132, 11515, 1105, 3613, 1106, 4470, 119, 102]


In [10]:
! pip install sentence-transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 1.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 12.9 MB/s eta 0:00:00
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125923 sha256=bcff1ce2662999f2c359263bb70fad9830d83dc76b0c7fbf93676e9a6c702ca7
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built sentence-transformers


In [11]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')
sentences = ['This framework generates embeddings for each input sentence',
    'Sentences are passed as a list of string.',
    'The quick brown fox jumps over the lazy dog.']
embeddings = model.encode(sentences)

#Print the embeddings
for sentence, embedding in zip(sentences, embeddings):
    print("Sentence:", sentence)
    print("Embedding:", embedding)
    print("")

.gitattributes:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

data_config.json:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

train_script.py:   0%|          | 0.00/13.2k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

Sentence: This framework generates embeddings for each input sentence
Embedding: [-1.37173552e-02 -4.28515449e-02 -1.56286024e-02  1.40537303e-02
  3.95537727e-02  1.21796280e-01  2.94334106e-02 -3.17524187e-02
  3.54959629e-02 -7.93139935e-02  1.75878741e-02 -4.04369719e-02
  4.97259349e-02  2.54912246e-02 -7.18700588e-02  8.14968869e-02
  1.47069141e-03  4.79626991e-02 -4.50336412e-02 -9.92174670e-02
 -2.81769745e-02  6.45046085e-02  4.44670543e-02 -4.76217009e-02
 -3.52952331e-02  4.38671783e-02 -5.28566055e-02  4.33063833e-04
  1.01921506e-01  1.64072234e-02  3.26996595e-02 -3.45986746e-02
  1.21339476e-02  7.94870779e-02  4.58345609e-03  1.57777797e-02
 -9.68206208e-03  2.87625659e-02 -5.05805984e-02 -1.55793717e-02
 -2.87906546e-02 -9.62280575e-03  3.15556750e-02  2.27349028e-02
  8.71449187e-02 -3.85027491e-02 -8.84718448e-02 -8.75498448e-03
 -2.12343335e-02  2.08923239e-02 -9.02077407e-02 -5.25732562e-02
 -1.05638904e-02  2.88310610e-02 -1.61455162e-02  6.17837207e-03
 -1.23234

At this point, go ahead and explore with the vector representation (the "embedding") of any sentence (or string of text, more generally), looking at the tokenized form, the list of token_id integers, or compute cosine similarities between the embeddings:

In [12]:
words = ["quick", "fast", "red", "blue", "ferari"]
single_word_embeddings = model.encode(words)

for word, embed in zip(words, single_word_embeddings):
  print("word: ", word)
  print("embed: ", embed[0:10])
  print("")



word:  quick
embed:  [-0.01363505  0.02511056 -0.03966426 -0.00121545  0.03869091 -0.04272134
  0.03643535  0.00567384  0.00246003 -0.04250647]

word:  fast
embed:  [-0.01659232  0.06137965 -0.01092987  0.02365591 -0.0138125  -0.01203378
 -0.00972914 -0.05885596 -0.01261965 -0.0577055 ]

word:  red
embed:  [-0.02509159  0.00884627 -0.10083688  0.01320896  0.01490394  0.02841406
  0.15962426  0.01331032  0.03514304 -0.04301136]

word:  blue
embed:  [-0.06580827  0.0203764  -0.05504949 -0.00301157  0.01343209  0.02449333
  0.20061415 -0.00983796  0.04382765 -0.01033155]

word:  ferari
embed:  [ 0.00451991  0.08644823 -0.12962112  0.05201175  0.01814397 -0.07465909
  0.07894592  0.05689763 -0.00582556 -0.09301732]



In [13]:
# prompt: python code to compute the matrix of cosines between all of the pairs of words in the list above.

from sklearn.metrics.pairwise import cosine_similarity
# Compute the cosine similarity between all pairs of words
word_embeddings = model.encode(words)
word_similarities = cosine_similarity(word_embeddings)
# Print the word similarities
print(word_similarities)


[[1.0000001  0.6515874  0.3388258  0.33914232 0.28320336]
 [0.6515874  1.         0.32009655 0.30601805 0.26345903]
 [0.3388258  0.32009655 1.         0.72944736 0.26313198]
 [0.33914232 0.30601805 0.72944736 1.         0.22827557]
 [0.28320336 0.26345903 0.26313198 0.22827557 0.99999976]]


In [14]:
# prompt: python code for computing cosine similarity between sentence vector embeddings from the above tokenizer and model

from scipy.spatial.distance import cosine
for sentence in sentences:
    print("Sentence:", sentence)
print("")
print("Cosine similarity between the first two sentences:", cosine(embeddings[0], embeddings[1]))
print("Cosine similarity between the second and third sentences:", cosine(embeddings[1], embeddings[2]))
print("Cosine similarity between the first and third sentences:", cosine(embeddings[0], embeddings[2]))


Sentence: This framework generates embeddings for each input sentence
Sentence: Sentences are passed as a list of string.
Sentence: The quick brown fox jumps over the lazy dog.

Cosine similarity between the first two sentences: 0.4619206190109253
Cosine similarity between the second and third sentences: 0.8964101523160934
Cosine similarity between the first and third sentences: 0.8819436207413673


In [19]:
# prompt: I want to getenereate some python code for contextual BERT embedding of all the words in the sentence
# Sentence # 1 "The crane extended its long neck to catch fish." (Here, "crane" refers to the bird.)"
# Sentence #2 "The construction site used a large crane to lift the steel beams." (Here, "crane" refers to the lifting machinery.)

model = SentenceTransformer('all-MiniLM-L6-v2')
sentences = ["The crane extended its long neck to catch fish.",
    "The construction site used a large crane to lift the steel beams."]
embeddings = model.encode(sentences)

#Print the embeddings
for sentence, embedding in zip(sentences, embeddings):
    print("Sentence:", sentence)
    print("Embedding:", embedding)
    print("")


Sentence: The crane extended its long neck to catch fish.
Embedding: [-5.87200485e-02  1.02601320e-01 -3.56601216e-02 -6.25853613e-03
 -1.32784154e-02  2.28056591e-02 -2.35999301e-02  3.77599671e-02
 -3.75212803e-02 -2.35247836e-02  1.12733401e-01 -6.35664072e-03
 -2.44954433e-02 -4.65563647e-02 -5.06110527e-02  2.95786113e-02
 -3.82066369e-02  4.15864524e-05 -4.70185801e-02  2.38030571e-02
 -6.93340525e-02  4.85518724e-02 -6.96808007e-03  2.27451045e-02
 -8.93104076e-02  5.04716523e-02 -1.22001439e-01  2.11864188e-02
  6.83772936e-02 -2.36179354e-03  3.87494937e-02 -1.73341446e-02
  6.01772368e-02 -1.30566973e-02 -6.63362592e-02  9.76945683e-02
  2.13158261e-02 -9.61477344e-04 -1.69728342e-02  6.77496344e-02
  8.88748467e-02  6.27066121e-02  1.20161567e-02  7.15643913e-02
 -8.12022239e-02  1.82667598e-02 -5.55286482e-02 -5.60541488e-02
  2.29245033e-02 -1.63580887e-02 -7.96118975e-02 -3.73488776e-02
 -3.56313260e-03  4.81040962e-02 -2.67710350e-02  9.09071192e-02
 -3.80920805e-02 -3.1

In [20]:
# prompt: now that we can we now choose another #3 sentence where the ambiguous word(s) have a different meaning and generate BERT embeddings for this sentence.

sentences = ["The crane extended its long neck to catch fish.",
    "The construction site used a large crane to lift the steel beams.",
    "The crane is a bird."]
embeddings = model.encode(sentences)

#Print the embeddings
for sentence, embedding in zip(sentences, embeddings):
    print("Sentence:", sentence)
    print("Embedding:", embedding)
    print("")


Sentence: The crane extended its long neck to catch fish.
Embedding: [-5.87200485e-02  1.02601320e-01 -3.56601216e-02 -6.25853613e-03
 -1.32784154e-02  2.28056591e-02 -2.35999301e-02  3.77599671e-02
 -3.75212803e-02 -2.35247836e-02  1.12733401e-01 -6.35664072e-03
 -2.44954433e-02 -4.65563647e-02 -5.06110527e-02  2.95786113e-02
 -3.82066369e-02  4.15864524e-05 -4.70185801e-02  2.38030571e-02
 -6.93340525e-02  4.85518724e-02 -6.96808007e-03  2.27451045e-02
 -8.93104076e-02  5.04716523e-02 -1.22001439e-01  2.11864188e-02
  6.83772936e-02 -2.36179354e-03  3.87494937e-02 -1.73341446e-02
  6.01772368e-02 -1.30566973e-02 -6.63362592e-02  9.76945683e-02
  2.13158261e-02 -9.61477344e-04 -1.69728342e-02  6.77496344e-02
  8.88748467e-02  6.27066121e-02  1.20161567e-02  7.15643913e-02
 -8.12022239e-02  1.82667598e-02 -5.55286482e-02 -5.60541488e-02
  2.29245033e-02 -1.63580887e-02 -7.96118975e-02 -3.73488776e-02
 -3.56313260e-03  4.81040962e-02 -2.67710350e-02  9.09071192e-02
 -3.80920805e-02 -3.1

In [21]:
# prompt: can we now Compare the embeddings of the ambiguous word(s) in the two sentences to illustrate how their vector representations change with context.
# Also, observe the embeddings of words whose meanings do not change across sentences to understand the stability of their vector representations.

model = SentenceTransformer('all-MiniLM-L6-v2')
sentences = ["The crane extended its long neck to catch fish.",
    "The construction site used a large crane to lift the steel beams.",
    "The crane is a bird."]
embeddings = model.encode(sentences)

#Print the embeddings
for sentence, embedding in zip(sentences, embeddings):
    print("Sentence:", sentence)
    print("Embedding:", embedding)
    print("")

print("Cosine similarity between the first two sentences:", cosine(embeddings[0], embeddings[1]))
print("Cosine similarity between the second and third sentences:", cosine(embeddings[1], embeddings[2]))
print("Cosine similarity between the first and third sentences:", cosine(embeddings[0], embeddings[2]))


Sentence: The crane extended its long neck to catch fish.
Embedding: [-5.87200485e-02  1.02601320e-01 -3.56601216e-02 -6.25853613e-03
 -1.32784154e-02  2.28056591e-02 -2.35999301e-02  3.77599671e-02
 -3.75212803e-02 -2.35247836e-02  1.12733401e-01 -6.35664072e-03
 -2.44954433e-02 -4.65563647e-02 -5.06110527e-02  2.95786113e-02
 -3.82066369e-02  4.15864524e-05 -4.70185801e-02  2.38030571e-02
 -6.93340525e-02  4.85518724e-02 -6.96808007e-03  2.27451045e-02
 -8.93104076e-02  5.04716523e-02 -1.22001439e-01  2.11864188e-02
  6.83772936e-02 -2.36179354e-03  3.87494937e-02 -1.73341446e-02
  6.01772368e-02 -1.30566973e-02 -6.63362592e-02  9.76945683e-02
  2.13158261e-02 -9.61477344e-04 -1.69728342e-02  6.77496344e-02
  8.88748467e-02  6.27066121e-02  1.20161567e-02  7.15643913e-02
 -8.12022239e-02  1.82667598e-02 -5.55286482e-02 -5.60541488e-02
  2.29245033e-02 -1.63580887e-02 -7.96118975e-02 -3.73488776e-02
 -3.56313260e-03  4.81040962e-02 -2.67710350e-02  9.09071192e-02
 -3.80920805e-02 -3.1

Let us now look at a different way to code it to see if there are any differences and to know a different way to do. Maybe we can see if there is a difference in prformance.

In [25]:
# Import necessary libraries
import torch  # PyTorch library, used for handling tensors (a form of data representation).
from transformers import AutoModel, AutoTokenizer  # These are from the Hugging Face Transformers library.


# Load the tokenizer and model
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
# ^ This loads a pre-trained tokenizer specific to the 'bert-base-uncased' model.
# The tokenizer's job is to convert text into a format that the model can understand.

model = AutoModel.from_pretrained("bert-base-uncased")
# ^ This loads the actual BERT model that will be used to generate embeddings.

# Example sentences
sentences = ["The crane extended its long neck to catch fish.",
             "The construction site used a large crane to lift the steel beams."]
# ^ These are the two sentences we want to analyze. The word 'crane' has different meanings in each.

# Tokenize the sentences and convert to PyTorch tensors
inputs = tokenizer(sentences, padding=True, truncation=True, return_tensors="pt")
# ^ This line tokenizes the sentences, turning the text into a series of numeric tokens.
# Padding is added to ensure both sentences are of equal length for processing.
# The tokens are then converted into PyTorch tensors, which are a type of multi-dimensional matrix used in deep learning.

# Generate embeddings
with torch.no_grad():
    outputs = model(**inputs)
# ^ This block of code passes the tokenized sentences to the BERT model to get embeddings.
# 'torch.no_grad()' is used to tell PyTorch not to calculate gradients in this step, as we're only doing forward-pass computations.

# The embeddings are in the last hidden state
embeddings = outputs.last_hidden_state
# ^ The 'last_hidden_state' attribute contains the embeddings for each token in the sentences.

# Find the index of the word "crane" in each sentence
crane_indices = [inputs.input_ids[i].tolist().index(tokenizer.convert_tokens_to_ids('crane')) for i in range(len(sentences))]
# ^ This line finds the position (index) of the word 'crane' in each tokenized sentence.
# 'input_ids' are the numeric representations of tokens in the sentences.

# Extract the embeddings for the word "crane" in each context
crane_embeddings = [embeddings[i][crane_index] for i, crane_index in enumerate(crane_indices)]
# ^ Here, we extract the specific embeddings for the word 'crane' from each sentence,
# using the indices we found in the previous step.

# Print the embeddings for "crane" in each sentence
for i, emb in enumerate(crane_embeddings):
    print(f"Embedding for 'crane' in sentence {i+1}:")
    print(emb)
    print()

# Compare embeddings using cosine similarity
from scipy.spatial.distance import cosine

# Calculate cosine similarity (1 - cosine distance) between the embeddings of "crane" in the two sentences
similarity = 1 - cosine(crane_embeddings[0], crane_embeddings[1])
print("Cosine similarity between the embeddings of 'crane' in the two contexts:", similarity)
# ^ Finally, we use the cosine similarity metric to compare the embeddings of 'crane' from both sentences.
# Cosine similarity measures the cosine of the angle between two vectors; in this context, it indicates how similar the embeddings are.
# A value close to 1 means very similar, and a value close to -1 means very different.


Embedding for 'crane' in sentence 1:
tensor([ 1.1167e+00,  1.3815e-01, -7.4214e-01,  2.0002e-01,  1.4949e-01,
        -1.8379e-01, -4.8734e-01,  1.1798e+00, -4.1960e-01, -3.9175e-01,
         3.8725e-01, -3.9205e-01, -9.8072e-02,  2.3032e-01, -5.3509e-01,
        -1.5606e-01, -6.3832e-02,  5.7545e-02,  1.2136e+00,  1.1901e-01,
        -1.3739e-01, -6.8480e-01,  3.6602e-02, -8.6589e-01,  7.8334e-01,
         3.1997e-01,  2.6621e-01,  5.7988e-01, -1.6359e-01,  7.2158e-01,
         8.6260e-01,  2.5783e-01,  9.1276e-01,  3.5247e-03, -5.0396e-01,
         1.1602e-02,  1.3682e-01, -2.8588e-01, -7.3894e-01, -7.6167e-02,
        -1.7945e-01, -1.3970e+00,  7.9656e-01,  2.9431e-01,  6.3923e-01,
        -3.9783e-01, -7.8660e-01, -9.8849e-02,  6.6371e-01, -6.2897e-01,
        -8.7572e-01,  1.1396e+00, -7.6272e-01, -3.1752e-01,  3.2087e-01,
         2.5518e-01, -4.5084e-01, -9.5422e-01,  5.9586e-01,  2.4992e-03,
        -4.5053e-01, -1.8594e-01,  3.1192e-01, -1.0866e-01, -2.4660e-01,
         7.332